[build]
  publish = "dist/public"
  command = "cp package.netlify.json package.json && cp vite.config.netlify.ts vite.config.ts && npm install && npm run build"

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"